# This is a basic workflow to help you get started with Actions
name: Gh-Page

on:
  push:
    branches: [master]

jobs:
  build:
   # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.2.0
      with:
        fetch-depth: 0
    
    # Builds unity project
    - name: Unity - Builder
      uses: webbertakken/unity-builder@v1.2
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      with:
        unityVersion: 2019.4.9f1
        targetPlatform: WebGL
        projectPath: game
        
    - name: Deploy to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: ./build/WebGL/.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
